version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore Maven Core updates
      - dependency-name: "org.apache.maven:*"
      # Checkstyle >=10 requires Java 11+
      - dependency-name: "com.puppycrawl.tools:checkstyle"
        versions: [">= 10.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
