language: java
env:
  - MAVEN_VERSION=3.0.5
  - MAVEN_VERSION=3.3.9
  - MAVEN_VERSION=3.5.2  
jdk:
  - openjdk7
  - oraclejdk8
install:
  - "mvn -N io.takari:maven:0.4.0:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode validate dependency:go-offline"
script: "./mvnw --show-version --errors --batch-mode clean verify site"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@apache.org
